### ISSUE TITLE
missing foo_periodic_msg_source

### ISSUE THREAD

**Issue by vsboost** [bastibl/gr-keyfob#1]
Hi there,
Installed using pybombs and am missing foo_periodic_msg_source block, not sure where to go from here.

Thanks

**Comment by bastibl** [comment]
Hi,
the periodic message source was a disabled block in the TX flow graph. It's available in this repository
https://github.com/bastibl/gr-foo
but not really needed here. I just pushed an updated version of the flow graph that uses the upstream "Message Strobe" block, which is pretty similar.
