### ISSUE TITLE
Python bindings are out of sync on maint-3.9 branch

### ISSUE THREAD

**Issue by drmpeg** [bastibl/gr-keyfob#11]
The Python bindings for ```keyfob_encode.h``` and ```parse_packet.h``` need to be regenerated. The ```BINDTOOL_HEADER_FILE_HASH``` in the bindings are out of sync causing ```cmake``` to fail.

**Comment by bastibl** [comment]
Thanks for letting me know. I just regenerated them. Hope it works, I'm still a 3.9-noob.
