### ISSUE TITLE
unknown base type "gr::sync_block"

### ISSUE THREAD

**Issue by ivannunyadambiz** [bastibl/gr-keyfob#14]
i'm not sure what i'm doing wrong. followed your instructions for gnuradio 3.8, but got this

```
  File "/home/ivan/gr-keyfob-maint-3.8/examples/keyfob_rx.py", line 36, in <module>
    import keyfob
  File "/usr/local/lib/python3.8/dist-packages/keyfob/__init__.py", line 18, in <module>
    from .keyfob_python import *
ImportError: generic_type: type "keyfob_encode" referenced unknown base type "gr::sync_block"
```

**Comment by bastibl** [comment]
Looks like you tried different versions and now have some artifacts left from previous installation attempts. Your `/usr/local/lib/python3.8/dist-packages/keyfob/__init__.py` is not from a 3.8 branch. Compare
3.8 version
https://github.com/bastibl/gr-keyfob/blob/maint-3.8/python/__init__.py
with 3.9 version
https://github.com/bastibl/gr-keyfob/blob/maint-3.9/python/__init__.py
