### ISSUE TITLE
Samplerate and Resamplerate

### ISSUE THREAD

**Issue by herrfeder** [bastibl/gr-keyfob#4]
Hello Bastian,

i don't have any Hella manufactured keys around here. So I'm trying to adapt your code for other key fobs. Therefore I have two questions on your keyfob_decode_wav example. 
Have you done any preprocessing to your input file or does it simply match with 48kHz Samplerate?
How did you calculate your Resamplerate(3400*5)?

Thank you in advance.

**Comment by bastibl** [comment]
The input file was recorded with a sample rate of 48kHz using gqrx.
The resample rate was chosen to have an integer number of samples per symbol.
The symbol rate was determined manually with a tool like inspectrum.

**Comment by herrfeder** [comment]
Okay, thank you, I'm not able to record a proper signal on 433MHz without downmixing with gqrx on samplerate of 48kHz. Inspectrum is great, I used baudline, but inspectrum is much better for this purpose.
