### ISSUE TITLE
No issue just a question.

### ISSUE THREAD

**Issue by ghost** [bastibl/gr-keyfob#5]
How can one make this work for a raspberry pi3 running 32 bit os?

**Comment by bastibl** [comment]
Yes, but that's more a feature of GNU Radio than of this module. I  don't know what's the easiest way to install GNU Radio (and OOT modules like this) on a Raspberry Pi. Maybe this is helpful
https://wiki.gnuradio.org/index.php/OE_PyBOMBS

If you have problems, it would be great if you could write to the GNU Radio mailing list. There are people who are much more experienced with ARM-based platforms.
