### ISSUE TITLE
Error: Gnuradio 3.8 not 3.9

### ISSUE THREAD

**Issue by ikarus23** [bastibl/gr-keyfob#8]
cmake request Gnuradio version 3.9. As far as I know the latest release was 3.8. Typo?

**Comment by ikarus23** [comment]
Ok, not sure now what exactly the issue is here. I'm using pybombs and apparently it installs Gnuradio 3.7. (https://github.com/gnuradio/pybombs/issues/547).

**Comment by bastibl** [comment]
This on purpose. GNU Radio pumped the API number for the development branch to 3.9, so the development branch of this module did the same. If you use GR 3.7, use the `maint-3.7` branch. If you use 3.8, use the `maint-3.8` branch as indicated in the readme.

**Comment by ikarus23** [comment]
Ok, my bad. Thanks for clearing that up. In that case it is the pybombs recipe for gnuradio needs some fixing.
